version: "3.9"

services:
  backend:
    build: .
    container_name: sardoba_bot_backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
