version: "3.9"

services:
  sardoba_warhouse_server:
    build: .
    image: sardoba_warhouse_server
    container_name: sardoba_warhouse_server
    restart: unless-stopped
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
